name: Update Vokabeln

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: GitHub API-Token setzen
        run: |
          FILE="latein/vokabeln.json"
          SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 https://api.github.com/repos/alex1-0/alex1-0.github.io/contents/$FILE | jq -r .sha)
          echo "SHA=$SHA" >> $GITHUB_ENV

      - name: Vokabeln aktualisieren
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          CONTENT=$(jq -Rs . < latein/vokabeln.json)
          gh api repos/alex1-0/alex1-0.github.io/contents/latein/vokabeln.json -X PUT \
            -F message="Automatisch aktualisierte Vokabeln" \
            -F content="$CONTENT" \
            -F sha="$SHA" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
